config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/delete_done'
  get 'home/delete_all'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def delete_done
        @delete_done = List.where(:completed => true).destroy_all
        redirect_to root_url, notice: 'All done items have been deleted'
    end

    def delete_all
        @delete_all = List.all.destroy_all
        redirect_to root_url, notice: 'All items have been deleted'
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    @list = List.new
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_url, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "lists/navbar" %>
    <div class="container">
      <%= render "lists/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <%= content_tag(:div, msg) %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: @list, local: true) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inline my2 my-lg-0">
    <%= f.text_field :description, class: "form-control mr-sm-2" %>
    <%= f.submit "Add To List", class: 'btn btn-outline-secondary my-2 my-sm-0' %>
  </div>
<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "To-Do List", root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"></ul>
    <%= render 'form_index' %>
  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<table class="table table-bordered">
  <tbody>
    <% @lists.each do |list| %>
      
      <% if list.completed %>
        <tr class="table-secondary">
          <td width="80%" class="striked-text"><%= link_to list.description, edit_list_path(list) %></td>  
          <td>
              <center>
                <%= form_for(list) do |f| %>
                  <%= f.text_field :description, type: 'hidden' %>
                  <%= f.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
                  <%= f.submit "Not done", class: 'btn btn-outline-secondary btn btn-sm' %>
                <% end %>
              </center>
          </td>   
          <td>
            <center>
              <%= link_to 'Delete', list, class: 'btn btn-outline-danger btn btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
            </center>
          </td>
        </tr>
      <% else %>
        <tr>
          <td width="80%"><%= link_to list.description, edit_list_path(list) %></td>
          <td>
            <center>
                <%= form_for(list) do |f| %>
                  <%= f.text_field :description, type: 'hidden' %>
                  <%= f.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
                  <%= f.submit "Done", class: 'btn btn-outline-secondary btn btn-sm' %>
                <% end %>
              </center>
          </td>  
          <td>
            <center>
              <%= link_to 'Delete', list, class: 'btn btn-outline-danger btn btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
            </center>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Delete Done Items', home_delete_done_path, data: { confirm: 'Are you sure you want to delete all done items?' }  %> | 
<%= link_to 'Delete All Items', home_delete_all_path, data: { confirm: 'Are you sure you want to delete all items?' }  %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>